---
- name: Deploy Docker container on Ubuntu
  hosts: slave-ec2
  become: yes
  vars:
    container_name: my-app-container       # Change this to your desired container name
    image_name: islamreda/nodejs-iamge:v1.4
         # Change this to your Docker image name
    container_port: 3000                    # Change this to your application's port

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ container_port }}:3000"  # Ensure this matches your application

    - name: Wait for the application to be up and running
      uri:
        url: "http://{{ ansible_host }}:{{ container_port }}"
        status_code: 200
        timeout: 60
      register: app_status
      retries: 6
      delay: 10
      until: app_status is succeeded

    - name: Print application URL
      debug:
        msg: "Application is running at http://{{ ansible_host }}:{{ container_port }}"
