---
- name: Build and run Docker image for web app
  hosts: slave-ec2
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: yes



    - name: Build Docker image using command
      command: docker build -t your-image-name:latest /home/sara/depi2
      become: yes


    - name: Run Docker container using command
      command: docker run -d --name my-web-container -p 3000:3000 your-image-name:latest

                                                                                                                                                                     
