---
- name: Deploy Application from Git on Docker
  hosts: ec2_instances
  become: yes
  vars:
    app_repo: "https://github.com/IslamReda/jenkins_nodejs_example.git"
    app_directory: ~/depi/app_container/jenkins_nodejs_example
    image_name: islamreda/nodejs-iamge:v1.4
    container_name: nodeapp
    container_port: 3000
    commit_hash: "c7bb260ce83efa4b0e1df537bf560d9d1e4f1e50"

  tasks:
    - name: Update package manager
      dnf:
        name: '*'
        state: latest

    - name: Install required packages
      dnf:
        name:
          - docker
          - git
          - python3
          - python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
        extra_args: --ignore-installed

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_directory }}"
        update: yes

    - name: Checkout specific commit
      command: git checkout {{ commit_hash }}
      args:
        chdir: "{{ app_directory }}"

    - name: Build Docker image
      docker_image:
        name: islamreda/nodejs-iamge:v1.4
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ container_port }}:3000"  # Ensure this matches your application

    - name: Wait for the application to be up and running
      uri:
        url: "http://{{ ansible_host }}:{{ container_port }}"
        status_code: 200
        timeout: 60
      register: app_status
      retries: 6
      delay: 10
      until: app_status is succeeded

    - name: Print application URL
      debug:
        msg: "Application is running at http://{{ ansible_host }}:{{ container_port }}"
 
